### PR TITLE
migrate androidx

### PR DESCRIPTION
**Pull request by arisros**
Issue [https://github.com/hui-z/audio_player/issues/5](url)

I think conflict flutter have another plugin from google.

migrate to androidx
[https://stackoverflow.com/questions/59496368/execution-failed-for-task-flutter-twitterverifyreleaseresources](url)

and compile sdk 28
[https://github.com/flutter/flutter/issues/46881](url)

### CODE REVIEW

**Comment by 00Zion00** [comment]
I create another branch for android x. I migrate to android x with Android Studio Refactor feature and I find some differences.  

image

**Comment by arisros** [comment]
Yaa already update refactor with android studio,

do you think it will be merge with `master-androidx` branch?

**Comment by 00Zion00** [comment]
yes. I will merge to master-androidx branch. Do you test this?

**Comment by arisros** [comment]
oh ok, yes already tested .

**Pull request merged**
